# Generated by Django 5.1.2 on 2025-01-06 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_creator_studygroup_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studygroup',
            name='members',
        ),
        migrations.AddField(
            model_name='studygroup',
            name='category',
            field=models.CharField(choices=[('math', 'Math'), ('trading', 'Trading'), ('coding', 'Coding'), ('history', 'History')], default='math', max_length=20),
        ),
        migrations.AlterField(
            model_name='studygroup',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
