# Generated by Django 5.1.2 on 2025-01-08 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_studygroup_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studygroup',
            name='category',
        ),
        migrations.RemoveField(
            model_name='studygroup',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='studygroup',
            name='members',
        ),
    ]
