# Generated by Django 5.1.2 on 2025-01-10 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_picture',
        ),
    ]
