# Generated by Django 5.1.2 on 2025-01-11 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_remove_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='study_groups',
            field=models.ManyToManyField(related_name='profiles', to='app.studygroup'),
        ),
    ]
