# Generated by Django 5.1.2 on 2025-01-11 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_profile_study_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studygroup',
            name='users',
        ),
    ]
