# Generated by Django 5.1.2 on 2025-01-11 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_remove_studygroup_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='study_groups',
            field=models.ManyToManyField(null=True, related_name='profiles', to='app.studygroup'),
        ),
    ]
