# Generated by Django 5.1.2 on 2025-01-11 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_profile_study_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='study_groups',
        ),
    ]
